# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425b27d00ddcc343ae268bf396d514cc35566442976b12ebdadbe05a64cd6b9636e77e2d22543a05f6dd063a1fa61c8b0f2254502df0baa1ee833d44f2d785e0

test:
  secret_key_base: 05ab6fdbcfa308c3675554b3abf66726bb59e5ce2ac55cf72f8688aa9211d9e9f293c440e7259d953ff031dce22e3cb77dfafc560f180ec6f3013157545da5c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
